all: ../output/All_Schools_Report_Card_SY1112_Chicago.csv \
	../output/Elementary_Attendance_SY1213_Chicago.csv \
	../output/Elementary_Closure_SY1213_Chicago.csv \
	../output/Elementary_Report_Card_SY1213_Chicago.csv \
	../output/Elementary_Report_Card_SY1314_Chicago.csv

include ../../generic.make
